import type { Language } from "@/context/LanguageContext";

// Dashboard-only translations (kept separate from the storefront dictionary).
export const dict = {
  en: {
    administration: "Administration",
    staffOnly: "Internal · Staff only",
    loading: "Loading…",
    couldNotLoad: "Could not load data",

    nav: { dashboard: "Dashboard", orders: "Orders", catalogue: "Catalogue", settings: "Settings" },

    kpi: {
      totalSales: "Total Sales",
      orders: "Orders",
      unitsSold: "Units Sold",
      avgOrderValue: "Avg Order Value",
      totalFragrances: "Total Fragrances",
      collectionValue: "Collection Value",
      averagePrice: "Average Price",
      activeOffers: "Active Offers",
    },

    overview: {
      newOrder: "New Order",
      collectionByCategory: "Collection by Category",
      highlights: "Highlights",
      mostPrecious: "Most Precious",
      mostAccessible: "Most Accessible",
      recentOrders: "Recent Orders",
      viewAll: "View all",
      noOrders: "No orders yet",
      recordFirst: "Record your first order",
    },

    orders: {
      title: "Orders",
      recordNew: "Record New Order",
      customerName: "Customer Name",
      fullName: "Full name",
      product: "Product",
      select: "Select…",
      size: "Size",
      quantity: "Quantity",
      status: "Status",
      estimatedTotal: "Estimated total:",
      addOrder: "Add Order",
      saving: "Saving…",
      errCustomer: "Enter a customer name",
      errProduct: "Choose a product",
      allOrders: "All Orders",
      noOrders: "No orders yet",
      useForm: "Use the form above to record your first order.",
      deleteOrder: "Delete order",
    },

    catalogue: {
      title: "Catalogue",
      search: "Search fragrances…",
      fragrances: "Fragrances",
      fragrance: "Fragrance",
      noResults: "No fragrances found",
      clearFilters: "Clear filters",
      addProduct: "Add Product",
      cancel: "Cancel",
      manage: "Manage",
      edit: "Edit",
      delete: "Delete",
      deleting: "Deleting…",
      builtIn: "Built-in",
      deleteConfirm: "Delete this product? This cannot be undone.",
      deleteFailed: "Could not delete the product. Please try again.",
    },

    addForm: {
      title: "Add New Product",
      subtitle: "It will appear on the website immediately.",
      nameEn: "Name (English)",
      nameAr: "Name (Arabic)",
      descEn: "Description (English)",
      descAr: "Description (Arabic)",
      price: "Price (EGP)",
      category: "Category",
      sizes: "Sizes (comma separated)",
      badge: "Badge (optional)",
      brand: "Brand / House (optional)",
      brandPlaceholder: "Defaults to store name",
      rating: "Rating 0–5 (optional)",
      notesTop: "Top Notes (optional)",
      notesHeart: "Heart Notes (optional)",
      notesBase: "Base Notes (optional)",
      notesPlaceholder: "e.g. Rose, Amber, Oud",
      none: "None",
      image: "Image",
      pickExisting: "Choose existing",
      upload: "Upload image",
      save: "Save Product",
      saving: "Saving…",
      added: "Product added to the website",
      errName: "Enter both English and Arabic names",
      errPrice: "Enter a valid price",
    },

    editForm: {
      title: "Edit Product",
      back: "Back to Catalogue",
      notFound: "Product not found",
      notEditable: "Built-in catalogue products can't be edited here.",
      save: "Save Changes",
      saving: "Saving…",
      saved: "Changes saved",
      delete: "Delete Product",
      deleting: "Deleting…",
      stock: "Stock",
      originalPrice: "Original price (optional)",
      notesTitle: "Fragrance Notes & Icons",
      notesSubtitle:
        "Add notes per layer and an optional icon/image for each. The card shows the icon when set, otherwise a curated glyph.",
      notesTop: "Top Notes",
      notesHeart: "Heart Notes",
      notesBase: "Base Notes",
      addNote: "Add note",
      notePlaceholder: "Note name (e.g. Rose)",
      noteImagePlaceholder: "Image URL (optional)",
      uploadNote: "Uploading",
    },

    table: {
      customer: "Customer",
      product: "Product",
      qty: "Qty",
      status: "Status",
      total: "Total",
      size: "Size",
      fragrance: "Fragrance",
      category: "Category",
      price: "Price",
      order: "Order",
      payment: "Payment",
    },

    status: {
      PENDING: "Pending",
      PENDING_PAYMENT: "Pending Payment",
      AWAITING_CONFIRMATION: "Awaiting Confirmation",
      PROCESSING: "Processing",
      SHIPPED: "Shipped",
      DELIVERED: "Delivered",
      CANCELLED: "Cancelled",
      REFUNDED: "Refunded",
      PAYMENT_FAILED: "Payment Failed",
    },
    payment: {
      MOBILE_WALLET: "Mobile Wallet",
      APPLE_PAY: "Apple Pay",
      COD: "Cash on Delivery",
      CARD: "Card",
    },

    badge: {
      bestseller: "Bestseller",
      new: "New",
      limited: "Limited",
      offer: "Offer",
    },

    cat: {
      all: "All",
      oriental: "Oriental",
      floral: "Floral",
      woody: "Woody",
      fresh: "Fresh",
      powdery: "Powdery",
    } as Record<string, string>,

    egp: "EGP",
  },

  ar: {
    administration: "الإدارة",
    staffOnly: "داخلي · للموظفين فقط",
    loading: "جارٍ التحميل…",
    couldNotLoad: "تعذّر تحميل البيانات",

    nav: { dashboard: "لوحة التحكم", orders: "الطلبات", catalogue: "الكتالوج", settings: "الإعدادات" },

    kpi: {
      totalSales: "إجمالي المبيعات",
      orders: "الطلبات",
      unitsSold: "الوحدات المباعة",
      avgOrderValue: "متوسط قيمة الطلب",
      totalFragrances: "إجمالي العطور",
      collectionValue: "قيمة المجموعة",
      averagePrice: "متوسط السعر",
      activeOffers: "العروض الفعّالة",
    },

    overview: {
      newOrder: "طلب جديد",
      collectionByCategory: "المجموعة حسب الفئة",
      highlights: "أبرز العطور",
      mostPrecious: "الأغلى",
      mostAccessible: "الأنسب سعراً",
      recentOrders: "أحدث الطلبات",
      viewAll: "عرض الكل",
      noOrders: "لا توجد طلبات بعد",
      recordFirst: "سجّل أول طلب",
    },

    orders: {
      title: "الطلبات",
      recordNew: "تسجيل طلب جديد",
      customerName: "اسم العميل",
      fullName: "الاسم الكامل",
      product: "المنتج",
      select: "اختر…",
      size: "الحجم",
      quantity: "الكمية",
      status: "الحالة",
      estimatedTotal: "الإجمالي التقديري:",
      addOrder: "إضافة طلب",
      saving: "جارٍ الحفظ…",
      errCustomer: "أدخل اسم العميل",
      errProduct: "اختر منتجاً",
      allOrders: "كل الطلبات",
      noOrders: "لا توجد طلبات بعد",
      useForm: "استخدم النموذج أعلاه لتسجيل أول طلب.",
      deleteOrder: "حذف الطلب",
    },

    catalogue: {
      title: "الكتالوج",
      search: "ابحث عن عطر…",
      fragrances: "عطر",
      fragrance: "عطر",
      noResults: "لم يتم العثور على عطور",
      clearFilters: "مسح عوامل التصفية",
      addProduct: "إضافة منتج",
      cancel: "إلغاء",
      manage: "إدارة",
      edit: "تعديل",
      delete: "حذف",
      deleting: "جارٍ الحذف…",
      builtIn: "أساسي",
      deleteConfirm: "حذف هذا المنتج؟ لا يمكن التراجع عن ذلك.",
      deleteFailed: "تعذّر حذف المنتج. حاول مرة أخرى.",
    },

    addForm: {
      title: "إضافة منتج جديد",
      subtitle: "سيظهر على الموقع فوراً.",
      nameEn: "الاسم (إنجليزي)",
      nameAr: "الاسم (عربي)",
      descEn: "الوصف (إنجليزي)",
      descAr: "الوصف (عربي)",
      price: "السعر (ج.م)",
      category: "الفئة",
      sizes: "الأحجام (مفصولة بفواصل)",
      badge: "الشارة (اختياري)",
      brand: "الماركة / الدار (اختياري)",
      brandPlaceholder: "يُستخدم اسم المتجر افتراضياً",
      rating: "التقييم ٠–٥ (اختياري)",
      notesTop: "نوتات القمة (اختياري)",
      notesHeart: "نوتات القلب (اختياري)",
      notesBase: "نوتات القاعدة (اختياري)",
      notesPlaceholder: "مثال: ورد، عنبر، عود",
      none: "بدون",
      image: "الصورة",
      pickExisting: "اختر صورة موجودة",
      upload: "رفع صورة",
      save: "حفظ المنتج",
      saving: "جارٍ الحفظ…",
      added: "تمت إضافة المنتج إلى الموقع",
      errName: "أدخل الاسم بالإنجليزية والعربية",
      errPrice: "أدخل سعراً صحيحاً",
    },

    editForm: {
      title: "تعديل المنتج",
      back: "العودة إلى الكتالوج",
      notFound: "المنتج غير موجود",
      notEditable: "لا يمكن تعديل منتجات الكتالوج الأساسية من هنا.",
      save: "حفظ التغييرات",
      saving: "جارٍ الحفظ…",
      saved: "تم حفظ التغييرات",
      delete: "حذف المنتج",
      deleting: "جارٍ الحذف…",
      stock: "المخزون",
      originalPrice: "السعر الأصلي (اختياري)",
      notesTitle: "نوتات العطر والأيقونات",
      notesSubtitle:
        "أضف النوتات لكل طبقة مع أيقونة/صورة اختيارية لكل نوتة. تظهر الأيقونة عند تعيينها، وإلا تُعرض أيقونة منسّقة.",
      notesTop: "نوتات القمة",
      notesHeart: "نوتات القلب",
      notesBase: "نوتات القاعدة",
      addNote: "إضافة نوتة",
      notePlaceholder: "اسم النوتة (مثال: ورد)",
      noteImagePlaceholder: "رابط الصورة (اختياري)",
      uploadNote: "جارٍ الرفع",
    },

    table: {
      customer: "العميل",
      product: "المنتج",
      qty: "الكمية",
      status: "الحالة",
      total: "الإجمالي",
      size: "الحجم",
      fragrance: "العطر",
      category: "الفئة",
      price: "السعر",
      order: "الطلب",
      payment: "الدفع",
    },

    status: {
      PENDING: "قيد الانتظار",
      PENDING_PAYMENT: "بانتظار الدفع",
      AWAITING_CONFIRMATION: "بانتظار التأكيد",
      PROCESSING: "قيد المعالجة",
      SHIPPED: "تم الشحن",
      DELIVERED: "تم التوصيل",
      CANCELLED: "ملغي",
      REFUNDED: "مسترد",
      PAYMENT_FAILED: "فشل الدفع",
    },
    payment: {
      MOBILE_WALLET: "محفظة إلكترونية",
      APPLE_PAY: "Apple Pay",
      COD: "الدفع عند الاستلام",
      CARD: "بطاقة",
    },

    badge: {
      bestseller: "الأكثر مبيعاً",
      new: "جديد",
      limited: "محدود",
      offer: "عرض",
    },

    cat: {
      all: "الكل",
      oriental: "شرقي",
      floral: "زهري",
      woody: "خشبي",
      fresh: "منعش",
      powdery: "بودري",
    } as Record<string, string>,

    egp: "ج.م",
  },
} as const;

export type Dict = (typeof dict)[Language];
